import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/FormBuilder/ui/toaster";
import Main from "@/components/Layout/Main";
import { UserService } from "@/service/user/user.service";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userDetails = await UserService.getUserDetails();
  console.log(userDetails);

  return (
    <html lang="en">
      <body>
        <Main>{children}</Main>
        <Toaster />
      </body>
    </html>
  );
}
